"""empty message

Revision ID: d24ca7b0019f
Revises: 0db209a836c4
Create Date: 2026-05-03 12:05:19.075133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24ca7b0019f'
down_revision: Union[str, Sequence[str], None] = '0db209a836c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demos', sa.Column('avatar', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demos', 'avatar')
    # ### end Alembic commands ###
