llm_config:
  base_url: https://api.deepseek.com/
  api_key: sk-8985ce947fbf47e080e18e616a118a07
  model_name: deepseek-reasoner
  temperature: 0.7
  max_tokens: 8192
agent_config:
  max_iterations: 100
  max_retries: 3
  max_search_results: 10
mcp_config:
  mcpServers:
    amap-maps-streamableHTTP:
      transport: streamable_http
      enabled: true
      description: null
      env: null
      command: null
      args: null
      url: https://mcp.amap.com/mcp?key=00b05640cc55c0ba2b7f85e0b3f2e6e7
      headers: null
a2a_config:
  a2a_servers: []
